"""init schema

Revision ID: 2ca6d9cd10ef
Revises: 
Create Date: 2026-08-13 11:41:58.207936

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.models.base
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2ca6d9cd10ef'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('patient_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('oss_key', sa.Text(), nullable=False),
    sa.Column('masked_oss_key', sa.Text(), nullable=True),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
    ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caregivers',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('patient_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('called_by', sa.Text(), nullable=False),
    sa.Column('relation', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('push_token', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_table('lab_reports',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('patient_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.Text(), nullable=True),
    sa.Column('hospital', sa.Text(), nullable=True),
    sa.Column('asset_ids', sa.ARRAY(sa.String()).with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalations',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('patient_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('utterance_raw', sa.Text(), nullable=True),
    sa.Column('audio_asset_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column(
        'context_json',
        postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.Text(), 'sqlite'),
        nullable=True,
    ),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('reply_audio_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
    ),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['reply_audio_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_escalations_state_retry', 'escalations', ['state', 'next_retry_at'], unique=False
    )
    op.create_table('lab_items',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('report_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('ref_low', sa.Numeric(), nullable=True),
    sa.Column('ref_high', sa.Numeric(), nullable=True),
    sa.Column('flag', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['lab_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lab_items_report_code', 'lab_items', ['report_id', 'code'], unique=False)
    op.create_table('medications',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('patient_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('generic_code', sa.Text(), nullable=True),
    sa.Column('generic_name', sa.Text(), nullable=False),
    sa.Column('brand_name', sa.Text(), nullable=True),
    sa.Column('strength_value', sa.Numeric(), nullable=True),
    sa.Column('strength_unit', sa.Text(), nullable=True),
    sa.Column('dose_per_take', sa.Numeric(), nullable=False),
    sa.Column('times_per_day', sa.Integer(), nullable=False),
    sa.Column('timing_note', sa.Text(), nullable=True),
    sa.Column('usage_raw', sa.Text(), nullable=True),
    sa.Column('photo_asset_id', app.models.base.GUID(length=36), nullable=True),
    sa.Column('confirmed_by', app.models.base.GUID(length=36), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint(
        "status <> 'active' OR confirmed_at IS NOT NULL", name='active_requires_confirm'
    ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['caregivers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['photo_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doses',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('medication_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('patient_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medication_id', 'scheduled_at', name='uq_dose_med_time')
    )
    op.create_index('ix_doses_patient_time', 'doses', ['patient_id', 'scheduled_at'], unique=False)
    op.create_table('confirmation_events',
    sa.Column('id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('dose_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('patient_id', app.models.base.GUID(length=36), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('alarm_fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tapped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('dwell_ms', sa.Integer(), nullable=True),
    sa.Column('ring_index', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dose_id'], ['doses.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_events_patient_tapped', 'confirmation_events', ['patient_id', 'tapped_at'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_patient_tapped', table_name='confirmation_events')
    op.drop_table('confirmation_events')
    op.drop_index('ix_doses_patient_time', table_name='doses')
    op.drop_table('doses')
    op.drop_table('medications')
    op.drop_index('ix_lab_items_report_code', table_name='lab_items')
    op.drop_table('lab_items')
    op.drop_index('ix_escalations_state_retry', table_name='escalations')
    op.drop_table('escalations')
    op.drop_table('lab_reports')
    op.drop_table('caregivers')
    op.drop_table('assets')
    op.drop_table('patients')
    # ### end Alembic commands ###
